import 'dotenv/config';
import express from 'express'; import helmet from 'helmet'; import cors from 'cors'; import cookieParser from 'cookie-parser'; import rateLimit from 'express-rate-limit'; import jwt from 'jsonwebtoken'; import argon2 from 'argon2'; import {Pool} from 'pg'; import {z} from 'zod';
const app=express(); const pool=new Pool({connectionString:process.env.DATABASE_URL});
const JWT_SECRET=process.env.JWT_SECRET!; const PORT=Number(process.env.PORT||3000);
app.use(helmet()); app.use(express.json({limit:'1mb'})); app.use(cookieParser()); app.use(cors({origin:process.env.FRONTEND_ORIGIN?.split(',')||[],credentials:true}));
const authLimit=rateLimit({windowMs:15*60*1000,max:60,standardHeaders:true,legacyHeaders:false}); app.use('/auth',authLimit);
function normPhone(v:string){return v.replace(/\D/g,'');}
function sign(user:{id:string,role:'seller'|'admin'}){return jwt.sign(user,JWT_SECRET,{expiresIn:'7d'});}
function setSession(res:any,payload:any){res.cookie('lteze_session',sign(payload),{httpOnly:true,secure:process.env.COOKIE_SECURE==='true',sameSite:'lax',maxAge:7*86400000});}
function requireAuth(role?:'seller'|'admin'){return (req:any,res:any,next:any)=>{try{const t=req.cookies.lteze_session;if(!t) return res.status(401).json({error:'UNAUTHENTICATED'});const p:any=jwt.verify(t,JWT_SECRET);if(role&&p.role!==role)return res.status(403).json({error:'FORBIDDEN'});req.user=p;next();}catch{return res.status(401).json({error:'INVALID_SESSION'});}}}
const registerSchema=z.object({full_name:z.string().min(2).max(120),phone:z.string().min(7).max(30),region:z.string().min(2).max(120),birth_date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),password:z.string().min(8).max(128)});
app.get('/health',(_,res)=>res.json({ok:true,service:'lteze-backend'}));
app.post('/auth/register',async(req,res)=>{const p=registerSchema.parse(req.body);const phone=normPhone(p.phone);const hash=await argon2.hash(p.password);try{const r=await pool.query('INSERT INTO sellers(full_name,phone_normalized,region,birth_date,password_hash) VALUES($1,$2,$3,$4,$5) RETURNING id,full_name,phone_normalized,account_status',[p.full_name,phone,p.region,p.birth_date,hash]);res.status(201).json({seller:r.rows[0]});}catch(e:any){if(e.code==='23505')return res.status(409).json({error:'PHONE_ALREADY_REGISTERED'});res.status(500).json({error:'SERVER_ERROR'});}});
app.post('/auth/login',async(req,res)=>{const phone=normPhone(String(req.body.phone||''));const password=String(req.body.password||'');const r=await pool.query('SELECT id,phone_normalized,password_hash,account_status FROM sellers WHERE phone_normalized=$1',[phone]);if(!r.rowCount)return res.status(401).json({error:'INVALID_CREDENTIALS'});const s=r.rows[0];if(s.account_status!=='active')return res.status(403).json({error:'ACCOUNT_NOT_ACTIVE'});if(!await argon2.verify(s.password_hash,password))return res.status(401).json({error:'INVALID_CREDENTIALS'});setSession(res,{id:s.id,role:'seller'});res.json({ok:true});});
app.post('/auth/logout',(_,res)=>{res.clearCookie('lteze_session');res.json({ok:true});});
app.get('/seller/me',requireAuth('seller'),async(req:any,res)=>{const s=await pool.query('SELECT id,full_name,phone_normalized,region,birth_date,account_status FROM sellers WHERE id=$1',[req.user.id]);const sub=await pool.query('SELECT status,starts_at,expires_at FROM subscriptions WHERE seller_id=$1 ORDER BY created_at DESC LIMIT 1',[req.user.id]);res.json({seller:s.rows[0],subscription:sub.rows[0]||null});});
app.get('/seller/products',requireAuth('seller'),async(req:any,res)=>{const limit=Math.min(Number(req.query.limit||50),100),offset=Math.max(Number(req.query.offset||0),0);const r=await pool.query('SELECT p.id,p.name,p.description,p.price,p.image_url,p.visibility,p.category_id,c.name category_name FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.seller_id=$1 AND p.visibility<>\'deleted\' ORDER BY p.created_at DESC LIMIT $2 OFFSET $3',[req.user.id,limit,offset]);res.json({products:r.rows,limit,offset});});
const productSchema=z.object({name:z.string().min(1).max(200),description:z.string().max(5000).default(''),price:z.number().nonnegative(),image_url:z.string().url().optional().nullable(),category_id:z.string().uuid()});
app.post('/seller/products',requireAuth('seller'),async(req:any,res)=>{const p=productSchema.parse(req.body);const active=await pool.query("SELECT 1 FROM sellers s WHERE s.id=$1 AND s.account_status='active' AND EXISTS(SELECT 1 FROM subscriptions sub WHERE sub.seller_id=s.id AND sub.status='active' AND sub.expires_at>now())",[req.user.id]);if(!active.rowCount)return res.status(403).json({error:'SUBSCRIPTION_REQUIRED'});const r=await pool.query('INSERT INTO products(seller_id,name,description,price,image_url,category_id) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[req.user.id,p.name,p.description,p.price,p.image_url||null,p.category_id]);res.status(201).json({product:r.rows[0]});});
app.patch('/seller/products/:id/visibility',requireAuth('seller'),async(req:any,res)=>{const v=z.enum(['published','hidden_by_seller']).parse(req.body.visibility);const r=await pool.query('UPDATE products SET visibility=$1,updated_at=now() WHERE id=$2 AND seller_id=$3 AND visibility NOT IN (\'deleted\',\'hidden_subscription\',\'hidden_suspension\') RETURNING id,visibility',[v,req.params.id,req.user.id]);if(!r.rowCount)return res.status(404).json({error:'PRODUCT_NOT_FOUND_OR_LOCKED'});res.json({product:r.rows[0]});});
app.get('/categories',async(_,res)=>{const r=await pool.query('SELECT id,name,slug FROM categories WHERE active=true ORDER BY sort_order,name');res.json({categories:r.rows});});
app.get('/catalog',async(req,res)=>{const limit=Math.min(Number(req.query.limit||50),100),offset=Math.max(Number(req.query.offset||0),0);const r=await pool.query("SELECT p.id,p.name,p.description,p.price,p.image_url,c.name category_name,s.id seller_id FROM products p JOIN sellers s ON s.id=p.seller_id LEFT JOIN categories c ON c.id=p.category_id WHERE p.visibility='published' AND s.account_status='active' AND EXISTS(SELECT 1 FROM subscriptions sub WHERE sub.seller_id=s.id AND sub.status='active' AND sub.expires_at>now()) ORDER BY p.created_at DESC LIMIT $1 OFFSET $2",[limit,offset]);res.json({products:r.rows,limit,offset});});
app.post('/auth/password-reset-request',async(req,res)=>{const phone=normPhone(String(req.body.phone||''));await pool.query('SELECT id FROM sellers WHERE phone_normalized=$1',[phone]);res.json({ok:true,message:'If the account exists, a reset request can be reviewed by admin.'});});
app.post('/admin/login',async(req,res)=>{const phone=normPhone(String(req.body.phone||''));const pass=String(req.body.password||'');const adminPhone=normPhone(process.env.ADMIN_BOOTSTRAP_PHONE||'');if(phone!==adminPhone||!process.env.ADMIN_BOOTSTRAP_PASSWORD||pass!==process.env.ADMIN_BOOTSTRAP_PASSWORD)return res.status(401).json({error:'INVALID_CREDENTIALS'});setSession(res,{id:'bootstrap-admin',role:'admin'});res.json({ok:true});});
app.get('/admin/dashboard',requireAuth('admin'),async(_,res)=>{const q=await pool.query("SELECT (SELECT count(*) FROM sellers) sellers,(SELECT count(*) FROM sellers WHERE account_status='active') active_sellers,(SELECT count(*) FROM sellers WHERE account_status='pending') pending_sellers,(SELECT count(*) FROM sellers WHERE account_status='suspended') suspended_sellers,(SELECT count(*) FROM products WHERE visibility<>'deleted') products,(SELECT count(*) FROM products WHERE visibility<>'published') hidden_products");res.json(q.rows[0]);});
app.get('/admin/sellers',requireAuth('admin'),async(req,res)=>{const limit=Math.min(Number(req.query.limit||50),100),offset=Math.max(Number(req.query.offset||0),0);const r=await pool.query('SELECT id,full_name,phone_normalized,region,birth_date,account_status,created_at FROM sellers ORDER BY created_at DESC LIMIT $1 OFFSET $2',[limit,offset]);res.json({sellers:r.rows,limit,offset});});
app.post('/admin/sellers/:id/approve',requireAuth('admin'),async(req:any,res)=>{const r=await pool.query("UPDATE sellers SET account_status='active',approved_at=now() WHERE id=$1 RETURNING id,account_status",[req.params.id]);if(!r.rowCount)return res.status(404).json({error:'SELLER_NOT_FOUND'});await pool.query('INSERT INTO audit_logs(admin_id,action,seller_id) VALUES($1,$2,$3)',[req.user.id,'seller_approved',req.params.id]);res.json({seller:r.rows[0]});});
app.post('/admin/sellers/:id/suspend',requireAuth('admin'),async(req:any,res)=>{const reason=String(req.body.reason||'Admin suspension');const c=await pool.connect();try{await c.query('BEGIN');const r=await c.query("UPDATE sellers SET account_status='suspended',suspended_at=now(),suspension_reason=$2 WHERE id=$1 RETURNING id,account_status",[req.params.id,reason]);if(!r.rowCount){await c.query('ROLLBACK');return res.status(404).json({error:'SELLER_NOT_FOUND'});}await c.query("UPDATE products SET visibility='hidden_suspension',prior_visibility=visibility,hidden_reason='seller_suspended',updated_at=now() WHERE seller_id=$1 AND visibility IN ('published','hidden_by_seller')",[req.params.id]);await c.query('INSERT INTO audit_logs(admin_id,action,seller_id,reason) VALUES($1,$2,$3,$4)',[req.user.id,'seller_suspended',req.params.id,reason]);await c.query('COMMIT');res.json({ok:true});}catch(e){await c.query('ROLLBACK');res.status(500).json({error:'SERVER_ERROR'});}finally{c.release();}});
app.post('/admin/subscriptions/:sellerId',requireAuth('admin'),async(req:any,res)=>{const days=z.number().int().min(1).max(3650).parse(Number(req.body.days));const c=await pool.connect();try{await c.query('BEGIN');const r=await c.query('INSERT INTO subscriptions(seller_id,status,starts_at,expires_at,created_by) VALUES($1,\'active\',now(),now()+($2 || \' days\')::interval,$3) RETURNING *',[req.params.sellerId,days,req.user.id]);await c.query("UPDATE products SET visibility=CASE WHEN visibility='hidden_subscription' THEN COALESCE(prior_visibility,'published') ELSE visibility END, prior_visibility=NULL, hidden_reason=NULL, updated_at=now() WHERE seller_id=$1 AND visibility='hidden_subscription'",[req.params.sellerId]);await c.query('INSERT INTO audit_logs(admin_id,action,seller_id,metadata) VALUES($1,$2,$3,$4)',[req.user.id,'subscription_activated',req.params.sellerId,JSON.stringify({days})]);await c.query('COMMIT');res.status(201).json({subscription:r.rows[0]});}catch(e){await c.query('ROLLBACK');res.status(500).json({error:'SERVER_ERROR'});}finally{c.release();}});
async function expire(){await pool.query("UPDATE subscriptions SET status='expired' WHERE status='active' AND expires_at<=now()");await pool.query("UPDATE products p SET prior_visibility=p.visibility,visibility='hidden_subscription',hidden_reason='subscription_expired',updated_at=now() FROM sellers s WHERE p.seller_id=s.id AND p.visibility IN ('published','hidden_by_seller') AND EXISTS(SELECT 1 FROM subscriptions sub WHERE sub.seller_id=s.id AND sub.status='expired' AND sub.expires_at=(SELECT max(expires_at) FROM subscriptions WHERE seller_id=s.id AND status='expired')) AND NOT EXISTS(SELECT 1 FROM subscriptions sub2 WHERE sub2.seller_id=s.id AND sub2.status='active' AND sub2.expires_at>now())");}
setInterval(()=>expire().catch(()=>{}),60_000); expire().catch(()=>{});
app.use((err:any,_req:any,res:any,_next:any)=>{if(err?.issues)return res.status(400).json({error:'VALIDATION_ERROR',details:err.issues});res.status(500).json({error:'SERVER_ERROR'});});
app.listen(PORT,()=>console.log(`LTEZE backend listening on ${PORT}`));
